#!/bin/bash

# FlamApp Quick Start Script
# This script helps set up and build the FlamApp project

set -e

echo "🔥 FlamApp Quick Start Setup"
echo "============================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running on macOS or Linux
OS=$(uname -s)
echo "Detected OS: $OS"
echo ""

# Step 1: Check prerequisites
echo "📋 Step 1: Checking prerequisites..."

# Check Android SDK
if [ -z "$ANDROID_HOME" ]; then
    echo -e "${YELLOW}⚠️  ANDROID_HOME not set${NC}"
    echo "Please set ANDROID_HOME environment variable"
    echo "Example: export ANDROID_HOME=\$HOME/Library/Android/sdk"
    exit 1
else
    echo -e "${GREEN}✓ Android SDK found: $ANDROID_HOME${NC}"
fi

# Check Java
if ! command -v java &> /dev/null; then
    echo -e "${RED}✗ Java not found${NC}"
    echo "Please install Java JDK 8 or later"
    exit 1
else
    JAVA_VERSION=$(java -version 2>&1 | head -n 1)
    echo -e "${GREEN}✓ Java found: $JAVA_VERSION${NC}"
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${YELLOW}⚠️  Node.js not found (required for web viewer)${NC}"
    echo "Install from: https://nodejs.org/"
else
    NODE_VERSION=$(node --version)
    echo -e "${GREEN}✓ Node.js found: $NODE_VERSION${NC}"
fi

echo ""

# Step 2: Configure local.properties
echo "📝 Step 2: Configuring local.properties..."

if [ -f "local.properties" ]; then
    echo "local.properties already exists"
else
    cat > local.properties <<EOF
# Auto-generated by quick-start.sh
sdk.dir=$ANDROID_HOME
EOF
    echo -e "${GREEN}✓ Created local.properties${NC}"
fi

echo ""

# Step 3: Check OpenCV
echo "📦 Step 3: Checking OpenCV..."

OPENCV_DIR="app/src/main/jniLibs/opencv"

if [ ! -d "$OPENCV_DIR" ]; then
    echo -e "${YELLOW}⚠️  OpenCV not found${NC}"
    echo ""
    echo "Please download OpenCV Android SDK:"
    echo "1. Visit: https://opencv.org/releases/"
    echo "2. Download: opencv-4.8.0-android-sdk.zip"
    echo "3. Extract to: $OPENCV_DIR"
    echo ""
    echo "Or use the following commands:"
    echo "  cd ~/Downloads"
    echo "  wget https://github.com/opencv/opencv/releases/download/4.8.0/opencv-4.8.0-android-sdk.zip"
    echo "  unzip opencv-4.8.0-android-sdk.zip"
    echo "  cd -"
    echo "  mkdir -p $OPENCV_DIR"
    echo "  cp -r ~/Downloads/OpenCV-android-sdk/sdk/native/* $OPENCV_DIR/"
    echo ""
    read -p "Press Enter after setting up OpenCV..."
else
    echo -e "${GREEN}✓ OpenCV found${NC}"
fi

echo ""

# Step 4: Build Android app
echo "🏗️  Step 4: Building Android app..."

if [ -f "./gradlew" ]; then
    chmod +x ./gradlew
    echo "Running Gradle build..."
    ./gradlew assembleDebug
    echo -e "${GREEN}✓ Android build completed${NC}"
else
    echo -e "${RED}✗ gradlew not found${NC}"
    exit 1
fi

echo ""

# Step 5: Setup web viewer
echo "🌐 Step 5: Setting up web viewer..."

if [ -d "web" ]; then
    cd web
    
    if command -v npm &> /dev/null; then
        echo "Installing npm packages..."
        npm install
        
        echo "Building TypeScript..."
        npm run build
        
        echo -e "${GREEN}✓ Web viewer built successfully${NC}"
        cd ..
    else
        echo -e "${YELLOW}⚠️  npm not found, skipping web viewer setup${NC}"
        cd ..
    fi
else
    echo -e "${RED}✗ web directory not found${NC}"
fi

echo ""
echo "================================"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "================================"
echo ""
echo "📱 To install on Android device:"
echo "   1. Connect device via USB"
echo "   2. Enable USB debugging"
echo "   3. Run: adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "🌐 To run web viewer:"
echo "   cd web"
echo "   npx http-server . -p 8000"
echo "   Open: http://localhost:8000"
echo ""
echo "📚 For detailed instructions, see SETUP.md"
echo ""
