#!/bin/bash

# FlamApp - Interactive Setup Guide
# Run this script to get personalized setup instructions

echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║          🔥 FlamApp - Interactive Setup Assistant 🔥              ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "This script will check your system and guide you through setup."
echo ""

# Check 1: Java
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  Checking Java..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1)
    echo -e "${GREEN}✓ Java installed: $JAVA_VERSION${NC}"
else
    echo -e "${RED}✗ Java not found${NC}"
    echo "  Install Java from: https://www.oracle.com/java/technologies/downloads/"
    exit 1
fi
echo ""

# Check 2: Android Studio / Android SDK
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  Checking Android SDK..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

ANDROID_SDK=""
if [ -n "$ANDROID_HOME" ]; then
    ANDROID_SDK="$ANDROID_HOME"
    echo -e "${GREEN}✓ ANDROID_HOME set: $ANDROID_HOME${NC}"
elif [ -n "$ANDROID_SDK_ROOT" ]; then
    ANDROID_SDK="$ANDROID_SDK_ROOT"
    echo -e "${GREEN}✓ ANDROID_SDK_ROOT set: $ANDROID_SDK_ROOT${NC}"
elif [ -d "$HOME/Library/Android/sdk" ]; then
    ANDROID_SDK="$HOME/Library/Android/sdk"
    echo -e "${YELLOW}⚠️  Android SDK found at default location${NC}"
    echo "  Location: $HOME/Library/Android/sdk"
else
    echo -e "${RED}✗ Android SDK not found${NC}"
    echo ""
    echo "  ⚠️  You need to install Android Studio first!"
    echo ""
    echo "  📥 Download Android Studio from:"
    echo "     https://developer.android.com/studio"
    echo ""
    echo "  After installation:"
    echo "  1. Open Android Studio"
    echo "  2. Go to Preferences → Appearance & Behavior → System Settings → Android SDK"
    echo "  3. Note the SDK location (usually ~/Library/Android/sdk on Mac)"
    echo "  4. Install SDK Platform 34 and SDK Build-Tools"
    echo "  5. Install NDK (Side by side) from SDK Tools tab"
    echo ""
    read -p "Press Enter after installing Android Studio..."
    
    # Check again
    if [ -d "$HOME/Library/Android/sdk" ]; then
        ANDROID_SDK="$HOME/Library/Android/sdk"
        echo -e "${GREEN}✓ Android SDK found!${NC}"
    else
        echo -e "${RED}✗ Still not found. Please check installation.${NC}"
        exit 1
    fi
fi
echo ""

# Check 3: Update local.properties
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  Configuring local.properties..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

USERNAME=$(whoami)
cat > local.properties <<EOF
# Auto-generated by setup-interactive.sh
sdk.dir=$ANDROID_SDK
EOF

echo -e "${GREEN}✓ Created local.properties with SDK path${NC}"
echo "  SDK path: $ANDROID_SDK"
echo ""

# Check 4: NDK
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣  Checking Android NDK..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ -d "$ANDROID_SDK/ndk" ]; then
    NDK_VERSIONS=$(ls -d "$ANDROID_SDK/ndk"/* 2>/dev/null | head -n 1)
    if [ -n "$NDK_VERSIONS" ]; then
        echo -e "${GREEN}✓ NDK found: $NDK_VERSIONS${NC}"
    else
        echo -e "${YELLOW}⚠️  NDK directory exists but no versions found${NC}"
        echo "  Install NDK via Android Studio SDK Manager"
    fi
else
    echo -e "${YELLOW}⚠️  NDK not found${NC}"
    echo ""
    echo "  📥 To install NDK:"
    echo "  1. Open Android Studio"
    echo "  2. Go to Preferences → Appearance & Behavior → System Settings → Android SDK"
    echo "  3. Click 'SDK Tools' tab"
    echo "  4. Check 'NDK (Side by side)'"
    echo "  5. Check 'CMake'"
    echo "  6. Click 'Apply' to install"
    echo ""
fi
echo ""

# Check 5: OpenCV
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "5️⃣  Checking OpenCV Android SDK..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

OPENCV_DIR="app/src/main/jniLibs/opencv"
if [ -d "$OPENCV_DIR" ] && [ "$(ls -A $OPENCV_DIR)" ]; then
    echo -e "${GREEN}✓ OpenCV SDK found${NC}"
else
    echo -e "${RED}✗ OpenCV SDK not found${NC}"
    echo ""
    echo "  ⚠️  This is the MOST IMPORTANT step!"
    echo ""
    echo -e "${YELLOW}  📥 To download OpenCV:${NC}"
    echo ""
    echo "  Run these commands:"
    echo ""
    echo -e "${BLUE}  cd ~/Downloads"
    echo "  curl -L -o opencv-android.zip https://github.com/opencv/opencv/releases/download/4.8.0/opencv-4.8.0-android-sdk.zip"
    echo "  unzip opencv-android.zip"
    echo "  cd -"
    echo "  mkdir -p app/src/main/jniLibs/opencv"
    echo -e "  cp -r ~/Downloads/OpenCV-android-sdk/sdk/native/* app/src/main/jniLibs/opencv/${NC}"
    echo ""
    echo "  OR visit: https://opencv.org/releases/"
    echo ""
    read -p "Press Enter after downloading OpenCV..."
fi
echo ""

# Check 6: Node.js (for web viewer)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "6️⃣  Checking Node.js (for web viewer)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    echo -e "${GREEN}✓ Node.js installed: $NODE_VERSION${NC}"
else
    echo -e "${YELLOW}⚠️  Node.js not found (optional for web viewer)${NC}"
    echo "  Install from: https://nodejs.org/"
fi
echo ""

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Setup Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Next steps:"
echo ""
echo -e "${GREEN}1️⃣  Build the Android app:${NC}"
echo "   ./gradlew assembleDebug"
echo ""
echo -e "${GREEN}2️⃣  Connect your Android device via USB${NC}"
echo "   - Enable USB debugging in Developer Options"
echo "   - Check connection: adb devices"
echo ""
echo -e "${GREEN}3️⃣  Install the app:${NC}"
echo "   adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo -e "${YELLOW}4️⃣  (Optional) Setup web viewer:${NC}"
echo "   cd web && npm install && npm run build"
echo "   npx http-server . -p 8000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔥 Ready to build? Run: ./gradlew assembleDebug"
echo ""
